// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.0
// source: chunk.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkService_ReadChunk_FullMethodName   = "/gfs.ChunkService/ReadChunk"
	ChunkService_CheckChunk_FullMethodName  = "/gfs.ChunkService/CheckChunk"
	ChunkService_PushData_FullMethodName    = "/gfs.ChunkService/PushData"
	ChunkService_CommitWrite_FullMethodName = "/gfs.ChunkService/CommitWrite"
)

// ChunkServiceClient is the client API for ChunkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChunkService handles all chunk server operations
type ChunkServiceClient interface {
	// ReadChunk retrieves data from a chunk
	ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error)
	// CheckChunk verifies if server has a chunk
	CheckChunk(ctx context.Context, in *CheckChunkRequest, opts ...grpc.CallOption) (*CheckChunkResponse, error)
	// Write Phase 1: Client pushes data to all replicas
	PushData(ctx context.Context, in *PushDataRequest, opts ...grpc.CallOption) (*PushDataResponse, error)
	// Write Phase 2: Client tells primary to commit
	CommitWrite(ctx context.Context, in *CommitWriteRequest, opts ...grpc.CallOption) (*CommitWriteResponse, error)
}

type chunkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkServiceClient(cc grpc.ClientConnInterface) ChunkServiceClient {
	return &chunkServiceClient{cc}
}

func (c *chunkServiceClient) ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadChunkResponse)
	err := c.cc.Invoke(ctx, ChunkService_ReadChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) CheckChunk(ctx context.Context, in *CheckChunkRequest, opts ...grpc.CallOption) (*CheckChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckChunkResponse)
	err := c.cc.Invoke(ctx, ChunkService_CheckChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) PushData(ctx context.Context, in *PushDataRequest, opts ...grpc.CallOption) (*PushDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushDataResponse)
	err := c.cc.Invoke(ctx, ChunkService_PushData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) CommitWrite(ctx context.Context, in *CommitWriteRequest, opts ...grpc.CallOption) (*CommitWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitWriteResponse)
	err := c.cc.Invoke(ctx, ChunkService_CommitWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkServiceServer is the server API for ChunkService service.
// All implementations must embed UnimplementedChunkServiceServer
// for forward compatibility.
//
// ChunkService handles all chunk server operations
type ChunkServiceServer interface {
	// ReadChunk retrieves data from a chunk
	ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error)
	// CheckChunk verifies if server has a chunk
	CheckChunk(context.Context, *CheckChunkRequest) (*CheckChunkResponse, error)
	// Write Phase 1: Client pushes data to all replicas
	PushData(context.Context, *PushDataRequest) (*PushDataResponse, error)
	// Write Phase 2: Client tells primary to commit
	CommitWrite(context.Context, *CommitWriteRequest) (*CommitWriteResponse, error)
	mustEmbedUnimplementedChunkServiceServer()
}

// UnimplementedChunkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkServiceServer struct{}

func (UnimplementedChunkServiceServer) ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadChunk not implemented")
}
func (UnimplementedChunkServiceServer) CheckChunk(context.Context, *CheckChunkRequest) (*CheckChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckChunk not implemented")
}
func (UnimplementedChunkServiceServer) PushData(context.Context, *PushDataRequest) (*PushDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushData not implemented")
}
func (UnimplementedChunkServiceServer) CommitWrite(context.Context, *CommitWriteRequest) (*CommitWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitWrite not implemented")
}
func (UnimplementedChunkServiceServer) mustEmbedUnimplementedChunkServiceServer() {}
func (UnimplementedChunkServiceServer) testEmbeddedByValue()                      {}

// UnsafeChunkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkServiceServer will
// result in compilation errors.
type UnsafeChunkServiceServer interface {
	mustEmbedUnimplementedChunkServiceServer()
}

func RegisterChunkServiceServer(s grpc.ServiceRegistrar, srv ChunkServiceServer) {
	// If the following call panics, it indicates UnimplementedChunkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkService_ServiceDesc, srv)
}

func _ChunkService_ReadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).ReadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_ReadChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).ReadChunk(ctx, req.(*ReadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_CheckChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).CheckChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_CheckChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).CheckChunk(ctx, req.(*CheckChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_PushData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).PushData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_PushData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).PushData(ctx, req.(*PushDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_CommitWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).CommitWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_CommitWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).CommitWrite(ctx, req.(*CommitWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkService_ServiceDesc is the grpc.ServiceDesc for ChunkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gfs.ChunkService",
	HandlerType: (*ChunkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadChunk",
			Handler:    _ChunkService_ReadChunk_Handler,
		},
		{
			MethodName: "CheckChunk",
			Handler:    _ChunkService_CheckChunk_Handler,
		},
		{
			MethodName: "PushData",
			Handler:    _ChunkService_PushData_Handler,
		},
		{
			MethodName: "CommitWrite",
			Handler:    _ChunkService_CommitWrite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chunk.proto",
}
