// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: chunk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadChunkRequest asks server for chunk data
type ReadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkRequest) Reset() {
	*x = ReadChunkRequest{}
	mi := &file_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkRequest) ProtoMessage() {}

func (x *ReadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkRequest.ProtoReflect.Descriptor instead.
func (*ReadChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *ReadChunkRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

// ReadChunkResponse returns the chunk data
type ReadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkResponse) Reset() {
	*x = ReadChunkResponse{}
	mi := &file_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkResponse) ProtoMessage() {}

func (x *ReadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkResponse.ProtoReflect.Descriptor instead.
func (*ReadChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *ReadChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CheckChunkRequest checks if server has a chunk
type CheckChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChunkRequest) Reset() {
	*x = CheckChunkRequest{}
	mi := &file_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChunkRequest) ProtoMessage() {}

func (x *CheckChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChunkRequest.ProtoReflect.Descriptor instead.
func (*CheckChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *CheckChunkRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

// CheckChunkResponse indicates if chunk exists
type CheckChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChunkResponse) Reset() {
	*x = CheckChunkResponse{}
	mi := &file_chunk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChunkResponse) ProtoMessage() {}

func (x *CheckChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChunkResponse.ProtoReflect.Descriptor instead.
func (*CheckChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{3}
}

func (x *CheckChunkResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type PushDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"` // unique ID for this write
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDataRequest) Reset() {
	*x = PushDataRequest{}
	mi := &file_chunk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDataRequest) ProtoMessage() {}

func (x *PushDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDataRequest.ProtoReflect.Descriptor instead.
func (*PushDataRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{4}
}

func (x *PushDataRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *PushDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PushDataRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type PushDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDataResponse) Reset() {
	*x = PushDataResponse{}
	mi := &file_chunk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDataResponse) ProtoMessage() {}

func (x *PushDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDataResponse.ProtoReflect.Descriptor instead.
func (*PushDataResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{5}
}

func (x *PushDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommitWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	FromPrimary   bool                   `protobuf:"varint,4,opt,name=fromPrimary,proto3" json:"fromPrimary,omitempty"`
	Secondaries   []string               `protobuf:"bytes,5,rep,name=secondaries,proto3" json:"secondaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitWriteRequest) Reset() {
	*x = CommitWriteRequest{}
	mi := &file_chunk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitWriteRequest) ProtoMessage() {}

func (x *CommitWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitWriteRequest.ProtoReflect.Descriptor instead.
func (*CommitWriteRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{6}
}

func (x *CommitWriteRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *CommitWriteRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *CommitWriteRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CommitWriteRequest) GetFromPrimary() bool {
	if x != nil {
		return x.FromPrimary
	}
	return false
}

func (x *CommitWriteRequest) GetSecondaries() []string {
	if x != nil {
		return x.Secondaries
	}
	return nil
}

type CommitWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitWriteResponse) Reset() {
	*x = CommitWriteResponse{}
	mi := &file_chunk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitWriteResponse) ProtoMessage() {}

func (x *CommitWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitWriteResponse.ProtoReflect.Descriptor instead.
func (*CommitWriteResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{7}
}

func (x *CommitWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitWriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplicateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	SourceAddress string                 `protobuf:"bytes,2,opt,name=sourceAddress,proto3" json:"sourceAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateChunkRequest) Reset() {
	*x = ReplicateChunkRequest{}
	mi := &file_chunk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateChunkRequest) ProtoMessage() {}

func (x *ReplicateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateChunkRequest.ProtoReflect.Descriptor instead.
func (*ReplicateChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{8}
}

func (x *ReplicateChunkRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *ReplicateChunkRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

type ReplicateChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateChunkResponse) Reset() {
	*x = ReplicateChunkResponse{}
	mi := &file_chunk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateChunkResponse) ProtoMessage() {}

func (x *ReplicateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateChunkResponse.ProtoReflect.Descriptor instead.
func (*ReplicateChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicateChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_chunk_proto protoreflect.FileDescriptor

const file_chunk_proto_rawDesc = "" +
	"\n" +
	"\vchunk.proto\x12\x03gfs\"*\n" +
	"\x10ReadChunkRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"=\n" +
	"\x11ReadChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x11CheckChunkRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\",\n" +
	"\x12CheckChunkResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"V\n" +
	"\x0fPushDataRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\adata_id\x18\x03 \x01(\tR\x06dataId\"B\n" +
	"\x10PushDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa0\x01\n" +
	"\x12CommitWriteRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12 \n" +
	"\vfromPrimary\x18\x04 \x01(\bR\vfromPrimary\x12 \n" +
	"\vsecondaries\x18\x05 \x03(\tR\vsecondaries\"E\n" +
	"\x13CommitWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"U\n" +
	"\x15ReplicateChunkRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12$\n" +
	"\rsourceAddress\x18\x02 \x01(\tR\rsourceAddress\"2\n" +
	"\x16ReplicateChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcf\x02\n" +
	"\fChunkService\x12:\n" +
	"\tReadChunk\x12\x15.gfs.ReadChunkRequest\x1a\x16.gfs.ReadChunkResponse\x12=\n" +
	"\n" +
	"CheckChunk\x12\x16.gfs.CheckChunkRequest\x1a\x17.gfs.CheckChunkResponse\x127\n" +
	"\bPushData\x12\x14.gfs.PushDataRequest\x1a\x15.gfs.PushDataResponse\x12@\n" +
	"\vCommitWrite\x12\x17.gfs.CommitWriteRequest\x1a\x18.gfs.CommitWriteResponse\x12I\n" +
	"\x0eReplicateChunk\x12\x1a.gfs.ReplicateChunkRequest\x1a\x1b.gfs.ReplicateChunkResponseB\x05Z\x03/pbb\x06proto3"

var (
	file_chunk_proto_rawDescOnce sync.Once
	file_chunk_proto_rawDescData []byte
)

func file_chunk_proto_rawDescGZIP() []byte {
	file_chunk_proto_rawDescOnce.Do(func() {
		file_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chunk_proto_rawDesc), len(file_chunk_proto_rawDesc)))
	})
	return file_chunk_proto_rawDescData
}

var file_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chunk_proto_goTypes = []any{
	(*ReadChunkRequest)(nil),       // 0: gfs.ReadChunkRequest
	(*ReadChunkResponse)(nil),      // 1: gfs.ReadChunkResponse
	(*CheckChunkRequest)(nil),      // 2: gfs.CheckChunkRequest
	(*CheckChunkResponse)(nil),     // 3: gfs.CheckChunkResponse
	(*PushDataRequest)(nil),        // 4: gfs.PushDataRequest
	(*PushDataResponse)(nil),       // 5: gfs.PushDataResponse
	(*CommitWriteRequest)(nil),     // 6: gfs.CommitWriteRequest
	(*CommitWriteResponse)(nil),    // 7: gfs.CommitWriteResponse
	(*ReplicateChunkRequest)(nil),  // 8: gfs.ReplicateChunkRequest
	(*ReplicateChunkResponse)(nil), // 9: gfs.ReplicateChunkResponse
}
var file_chunk_proto_depIdxs = []int32{
	0, // 0: gfs.ChunkService.ReadChunk:input_type -> gfs.ReadChunkRequest
	2, // 1: gfs.ChunkService.CheckChunk:input_type -> gfs.CheckChunkRequest
	4, // 2: gfs.ChunkService.PushData:input_type -> gfs.PushDataRequest
	6, // 3: gfs.ChunkService.CommitWrite:input_type -> gfs.CommitWriteRequest
	8, // 4: gfs.ChunkService.ReplicateChunk:input_type -> gfs.ReplicateChunkRequest
	1, // 5: gfs.ChunkService.ReadChunk:output_type -> gfs.ReadChunkResponse
	3, // 6: gfs.ChunkService.CheckChunk:output_type -> gfs.CheckChunkResponse
	5, // 7: gfs.ChunkService.PushData:output_type -> gfs.PushDataResponse
	7, // 8: gfs.ChunkService.CommitWrite:output_type -> gfs.CommitWriteResponse
	9, // 9: gfs.ChunkService.ReplicateChunk:output_type -> gfs.ReplicateChunkResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chunk_proto_init() }
func file_chunk_proto_init() {
	if File_chunk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chunk_proto_rawDesc), len(file_chunk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chunk_proto_goTypes,
		DependencyIndexes: file_chunk_proto_depIdxs,
		MessageInfos:      file_chunk_proto_msgTypes,
	}.Build()
	File_chunk_proto = out.File
	file_chunk_proto_goTypes = nil
	file_chunk_proto_depIdxs = nil
}
