// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: master.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetChunkLocationsRequest asks master where a chunk is stored
type GetChunkLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkLocationsRequest) Reset() {
	*x = GetChunkLocationsRequest{}
	mi := &file_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkLocationsRequest) ProtoMessage() {}

func (x *GetChunkLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetChunkLocationsRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{0}
}

func (x *GetChunkLocationsRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// ChunkLocationResponse tells client which servers hold the chunk
type ChunkLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *ChunkMetadata         `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkLocationResponse) Reset() {
	*x = ChunkLocationResponse{}
	mi := &file_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkLocationResponse) ProtoMessage() {}

func (x *ChunkLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkLocationResponse.ProtoReflect.Descriptor instead.
func (*ChunkLocationResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkLocationResponse) GetChunk() *ChunkMetadata {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ChunkLocationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AllocateChunkRequest asks master to create a new chunk for a file
type AllocateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkRequest) Reset() {
	*x = AllocateChunkRequest{}
	mi := &file_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkRequest) ProtoMessage() {}

func (x *AllocateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunkRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateChunkRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// AllocateChunkResponse returns the newly allocated chunk metadata
type AllocateChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *ChunkMetadata         `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkResponse) Reset() {
	*x = AllocateChunkResponse{}
	mi := &file_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkResponse) ProtoMessage() {}

func (x *AllocateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkResponse.ProtoReflect.Descriptor instead.
func (*AllocateChunkResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{3}
}

func (x *AllocateChunkResponse) GetChunk() *ChunkMetadata {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *AllocateChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetFileMetadataRequest asks master for all chunks in a file
type GetFileMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataRequest) Reset() {
	*x = GetFileMetadataRequest{}
	mi := &file_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataRequest) ProtoMessage() {}

func (x *GetFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileMetadataRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// GetFileMetadataResponse returns the file's metadata
type GetFileMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *FileMetadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataResponse) Reset() {
	*x = GetFileMetadataResponse{}
	mi := &file_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataResponse) ProtoMessage() {}

func (x *GetFileMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetFileMetadataResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileMetadataResponse) GetMetadata() *FileMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetFileMetadataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_master_proto protoreflect.FileDescriptor

const file_master_proto_rawDesc = "" +
	"\n" +
	"\fmaster.proto\x12\x03gfs\x1a\fcommon.proto\"6\n" +
	"\x18GetChunkLocationsRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"W\n" +
	"\x15ChunkLocationResponse\x12(\n" +
	"\x05chunk\x18\x01 \x01(\v2\x12.gfs.ChunkMetadataR\x05chunk\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"2\n" +
	"\x14AllocateChunkRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"W\n" +
	"\x15AllocateChunkResponse\x12(\n" +
	"\x05chunk\x18\x01 \x01(\v2\x12.gfs.ChunkMetadataR\x05chunk\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x16GetFileMetadataRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"^\n" +
	"\x17GetFileMetadataResponse\x12-\n" +
	"\bmetadata\x18\x01 \x01(\v2\x11.gfs.FileMetadataR\bmetadata\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xf5\x01\n" +
	"\rMasterService\x12F\n" +
	"\rAllocateChunk\x12\x19.gfs.AllocateChunkRequest\x1a\x1a.gfs.AllocateChunkResponse\x12N\n" +
	"\x11GetChunkLocations\x12\x1d.gfs.GetChunkLocationsRequest\x1a\x1a.gfs.ChunkLocationResponse\x12L\n" +
	"\x0fGetFileMetadata\x12\x1b.gfs.GetFileMetadataRequest\x1a\x1c.gfs.GetFileMetadataResponseB\x05Z\x03/pbb\x06proto3"

var (
	file_master_proto_rawDescOnce sync.Once
	file_master_proto_rawDescData []byte
)

func file_master_proto_rawDescGZIP() []byte {
	file_master_proto_rawDescOnce.Do(func() {
		file_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)))
	})
	return file_master_proto_rawDescData
}

var file_master_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_master_proto_goTypes = []any{
	(*GetChunkLocationsRequest)(nil), // 0: gfs.GetChunkLocationsRequest
	(*ChunkLocationResponse)(nil),    // 1: gfs.ChunkLocationResponse
	(*AllocateChunkRequest)(nil),     // 2: gfs.AllocateChunkRequest
	(*AllocateChunkResponse)(nil),    // 3: gfs.AllocateChunkResponse
	(*GetFileMetadataRequest)(nil),   // 4: gfs.GetFileMetadataRequest
	(*GetFileMetadataResponse)(nil),  // 5: gfs.GetFileMetadataResponse
	(*ChunkMetadata)(nil),            // 6: gfs.ChunkMetadata
	(*FileMetadata)(nil),             // 7: gfs.FileMetadata
}
var file_master_proto_depIdxs = []int32{
	6, // 0: gfs.ChunkLocationResponse.chunk:type_name -> gfs.ChunkMetadata
	6, // 1: gfs.AllocateChunkResponse.chunk:type_name -> gfs.ChunkMetadata
	7, // 2: gfs.GetFileMetadataResponse.metadata:type_name -> gfs.FileMetadata
	2, // 3: gfs.MasterService.AllocateChunk:input_type -> gfs.AllocateChunkRequest
	0, // 4: gfs.MasterService.GetChunkLocations:input_type -> gfs.GetChunkLocationsRequest
	4, // 5: gfs.MasterService.GetFileMetadata:input_type -> gfs.GetFileMetadataRequest
	3, // 6: gfs.MasterService.AllocateChunk:output_type -> gfs.AllocateChunkResponse
	1, // 7: gfs.MasterService.GetChunkLocations:output_type -> gfs.ChunkLocationResponse
	5, // 8: gfs.MasterService.GetFileMetadata:output_type -> gfs.GetFileMetadataResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_master_proto_init() }
func file_master_proto_init() {
	if File_master_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_proto_goTypes,
		DependencyIndexes: file_master_proto_depIdxs,
		MessageInfos:      file_master_proto_msgTypes,
	}.Build()
	File_master_proto = out.File
	file_master_proto_goTypes = nil
	file_master_proto_depIdxs = nil
}
